### ISSUE TITLE
Error when using Express

### ISSUE THREAD

**Issue by ericksoncohen** [LudicrousDevelopment/Palladium#9]
/home/runner/Palladium/lib/server/index.js:20
    if (server!={}) server.on('request', (req, res) => {if(req.headers.useragent === 'googlebot') return res.writeHead(403).end('');})
                           ^

TypeError: server.on is not a function
    at new Smoke (/home/runner/Palladium/lib/server/index.js:20:28)
    at Object.<anonymous> (/home/runner/Palladium/examples/express-server/index.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by VasukipriyaKN** [comment]
try this

const server = http.createServer();
server.on('request', (request, response)

**Comment by EnderKingJ** [comment]
replace the server.on(“request”, (... with
server.use(...

**Comment by EnderKingJ** [comment]
Don’t include the “request”
